### ISSUE TITLE
Says "Idle" if I turn off file names

### ISSUE THREAD

**Issue by xdavidhu** [HelloWorld017/atom-discord#40]
If I turn off the file name option, in the description atom-discord puts "Idle", but I am not idle.

I think putting the text with the file type e.g. "Editing a Python file." would be more logical and understandable for others if file names are turned off.

![screen shot 2018-01-22 at 21 42 44](https://user-images.githubusercontent.com/18151245/35243464-4791b250-ffbd-11e7-9ae0-a334fe81819e.png)

Btw awesome package, got super hyped when I saw it at someone else on a server :D

**Comment by Ekidoxx** [comment]
Maybe it should display https://github.com/HelloWorld017/atom-discord/blob/29fabb2f121c145e1b6fae9870ec6420223a6012/i18n/en-US.json#L8 instead in such case?

**Comment by HelloWorld017** [comment]
@xdavidhu Would you show your settings about privacy & behaviors?
@Ekidoxx Unfortunately, 'editing-idle' of second one is the text which is shown when no files are opened. T_T

**Comment by Ekidoxx** [comment]
@HelloWorld017 Well... How about showing https://github.com/HelloWorld017/atom-discord/blob/29fabb2f121c145e1b6fae9870ec6420223a6012/i18n/en-US.json#L5 when no files are opened (which actually would sound more logical), and https://github.com/HelloWorld017/atom-discord/blob/29fabb2f121c145e1b6fae9870ec6420223a6012/i18n/en-US.json#L8 when file name shouldn't be displayed?

---

Since I get exactly same result:

![image](https://user-images.githubusercontent.com/14035306/35253322-11bae87c-ffe5-11e7-982c-0a46fb4c2e76.png)

**Comment by Ekidoxx** [comment]
Guess what, that also got fixed once I manually updated package with content of this repo...

![image](https://user-images.githubusercontent.com/14035306/35257650-d6e0918c-fffa-11e7-8080-d5c2bf615218.png)
![image](https://user-images.githubusercontent.com/14035306/35257691-12758158-fffb-11e7-99c7-b748475ff5a6.png)

**Comment by HelloWorld017** [comment]
Because of slow update, you should wait for about 15s to update!

**Comment by HelloWorld017** [comment]
I think this issue have been solved at a3dea3e3fb317e8044ea2cde5abf759fa16aa4a9. :D I'll upload to apm when testing #42 is finished.

**Comment by xdavidhu** [comment]
Just updated, it works really well! :D
Thank you for the quick response & fix!

![screen shot 2018-01-24 at 18 57 01](https://user-images.githubusercontent.com/18151245/35348452-675264f0-0138-11e8-9536-d2a386d13a1a.png)
